[workspace]
members = ["soulseek-rs-lib", "soulseek-rs"]
resolver = "2"

[workspace.package]
version = "0.2.1"
authors = ["Michel de Graaf"]
edition = "2021"
license = "MIT"
repository = "https://github.com/michel/soulseek-rs"
