[workspace]
members = ["soulseek-rs-lib", "soulseek-rs"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Michel de Graaf"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/soulseek-rs"
